import random


def generate_random_categories_name(num_icons=1):
    categories_name_list = [
        "Quantum Mechanics Accessories",
        "Galactic Culinary Delights",
        "Tropical Sock Patterns",
        "Ancient Mysteries Unveiled",
        "Cybernetic Pet Care",
        "Interstellar Jazz Fusion",
        "Retro-Futuristic Artifacts",
        "Virtual Reality Gardening",
        "Steampunk Fashion Essentials",
        "Exoplanet Mixology",
        "Biohazardous Home Decor",
        "Subterranean Adventure Gear",
        "Algorithmic Poetry",
        "Molecular Gastronomy Tools",
        "Transdimensional Puzzle Games",
        "Celestial Hairstyling Techniques",
        "Time-Traveler's Book Club",
        "Bioluminescent Camping Gear",
        "Neurological Fitness Programs",
        "Esoteric Weather Forecasting",
        "Cryptozoological Footwear",
        "Microgravity Yoga Apparel",
        "AI-Generated Haute Couture",
        "Holographic Board Games",
        "Intergalactic Farming Implements",
        "Paranormal Mix and Match Wardrobe",
        "Deep Sea Space Exploration Gear",
        "Extraterrestrial Mixology",
        "Cyberpunk Home Office Supplies",
        "Psychic Fitness Regimen",
        "Alien Communication Courses",
        "Post-Apocalyptic Gourmet Cooking",
        "Dystopian Dinosaur Fashion",
        "Virtual Aquarium Design",
        "Renaissance Time-Travel Art",
        "Interplanetary Dessert Recipes",
        "Artificial Intelligence Poetry",
        "Subatomic Particle Collectibles",
        "Future Archaeology Kits",
        "Biodegradable Spacesuit Fabrics",
        "Mythical Creature Taxidermy",
        "Quantum Computing Cookware",
        "Celestial Mix and Match Makeup",
        "Insectoid Fashion Trends",
        "Genetic Mutation Board Games",
        "Astrobiology Study Tools",
        "Retro Robotics Collectibles",
        "Space Cowboy Apparel",
        "Interdimensional Baking Utensils",
        "Virtual Reality Sustainable Living",
        "Ancient Civilization Tech Gadgets",
        "Extraterrestrial Fashion Magazines",
        "Neon Wilderness Survival Gear",
        "Post-Apocalyptic Ballroom Dancing",
        "Virtual Zookeeping Courses",
        "Galactic Mixology Recipes",
        "Cyberpunk Cat Furniture",
        "Ancient Alien Herbalism",
        "Time-Traveling Pet Accessories",
        "Exoplanetary Wildlife Photography",
        "Retro-Futuristic Dance Moves",
        "Subterranean Adventure Outfits",
        "Biomechanical Gardening Tools",
        "Quantum Physics Board Games",
        "Paranormal Hairstyling Techniques",
        "Insectoid Culinary Delights",
        "AI-Generated Sculpture Kits",
        "Celestial Fitness Wear",
        "Transdimensional Meditation Apps",
        "Dystopian Dinosaur Gardening",
        "Holographic Home Office Decor",
        "Future Archaeology Fashion",
        "Astrobiology Mix and Match Makeup",
        "Post-Apocalyptic Art Supplies",
        "Biodegradable Cyberpunk Fashion",
        "Mythical Creature Hairstyling Tools",
        "Quantum Computing Pet Care",
        "Ancient Civilization Mixology",
        "Neon Wilderness Survival Courses",
        "Cybernetic Insect Poetry",
        "Galactic DIY Home Improvement",
        "Retro Robotics Virtual Reality",
        "Extraterrestrial Baking Utensils",
        "Space Cowboy Board Games",
        "Interdimensional Insect Taxidermy",
        "Virtual Reality Sustainable Fashion",
        "Ancient Alien Dance Moves",
        "Time-Traveling Wildlife Photography",
        "Exoplanetary Mix and Match Wardrobe",
        "Cyberpunk Ballroom Dancing",
        "Insectoid Home Office Supplies",
        "AI-Generated Virtual Zookeeping",
        "Celestial Adventure Gear",
        "Transdimensional Mixology Recipes",
        "Dystopian Dinosaur Meditation Apps",
        "Holographic Alien Herbalism",
        "Future Archaeology Board Games",
        "Astrobiology Fashion Magazines",
        "Post-Apocalyptic Hairstyling Techniques",
        "Biodegradable Galactic Mixology",
        "Mythical Creature Home Office Decor",
        "Quantum Computing Dance Moves",
        "Ancient Civilization Cybernetic Pet Care",
        "Neon Wilderness Survival Gardening",
        "Cybernetic Insect Home Office Supplies",
        "Galactic DIY Home Improvement Courses",
        "Retro Robotics Mix and Match Wardrobe",
        "Extraterrestrial Meditation Apps",
        "Space Cowboy Culinary Delights",
        "Interdimensional Insect Taxidermy",
        "Virtual Reality Sustainable Fashion Trends",
        "Ancient Alien Adventure Outfits",
        "Time-Traveling Cyberpunk Poetry",
        "Exoplanetary Ballroom Dancing",
        "Cybernetic Board Games",
        "Insectoid Virtual Zookeeping",
        "AI-Generated Celestial Fashion",
        "Celestial Hairstyling Tools",
        "Transdimensional Mixology Tools",
        "Dystopian Dinosaur Sustainable Wildlife Photography",
        "Holographic Alien Dance Moves",
        "Future Archaeology Cyberpunk Fashion",
        "Astrobiology Baking Utensils"
    ]

    num_of_categories = min(num_icons, len(categories_name_list))

    select_random_icons = random.sample(categories_name_list, num_of_categories)

    # Convert the list to a string
    categories_string = ", ".join(select_random_icons)

    return categories_string
